import "../styles/globals.css";
import type { Metadata } from "next";
import { NavBar, Footer } from "@/components";

export const metadata: Metadata = {
  title: "Calgary House Fellowship",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray-50 antialiased`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
